CREATE TABLE [dbo].[sales]
(
	 cdc_key bigint NOT NULL,
company_id nvarchar(10) NOT NULL,
sales_channel_code nvarchar(255) NOT NULL,
pos_number nvarchar(255) NOT NULL,
transaction_number bigint NOT NULL,
line_no int NOT NULL,
receipt_no nvarchar(100) NOT NULL,
[date] datetime NOT NULL,
[time] datetime NOT NULL,
item_no nvarchar(255) NOT NULL,
variant_code nvarchar(255) NOT NULL,
item_id nvarchar(255) NOT NULL,
item_division_code nvarchar(255) NULL,
item_category_code nvarchar(255) NULL,
item_group_code nvarchar(255) NULL,
quantity decimal(38, 20) NOT NULL,
net_price decimal(38, 20) NOT NULL,
net_amount_lcy decimal(38, 20) NOT NULL,
net_amount_acy decimal(38, 20) NULL,
exchange_rate decimal(38, 20) NULL,
vat_amount decimal(38, 20) NOT NULL,
rounded_amount decimal(38, 20) NOT NULL,
line_discount decimal(38, 20) NOT NULL,
periodic_discount_type int NOT NULL,
periodic_discount_group nvarchar(20) NOT NULL,
periodic_discount_amount decimal(38, 20) NOT NULL,
other_discount_amount decimal(38, 20) NOT NULL,
total_discount_amount decimal(38, 20) NOT NULL,
staff_id nvarchar(50) NULL,
scale_operator_id nvarchar(5) NULL, 
     
    CONSTRAINT [FK_sales_company] FOREIGN KEY ([company_id]) REFERENCES [company]([id]),
    CONSTRAINT [FK_sales_company_id_item_no] FOREIGN KEY ([company_id],[item_no]) REFERENCES [item]([company_id],[item_no]), 
    CONSTRAINT [PK_sales] PRIMARY KEY ([company_id], [receipt_no], [sales_channel_code], [pos_number], [transaction_number], [line_no]), 
       
)
ON [FLOWBYTE_SALES];
