name: Deploy API to IIS

on:
  workflow_dispatch:
  push:
    branches:  [ dev, main ]
    paths:
      - 'Application/**'
      - 'Application.Client/**'
      - 'Application.Shared/**'

jobs:
  build:
    runs-on: self-hosted

    # Dynamically pick environment: if branch is 'dev', use 'test'; else use 'prod'
    environment: ${{ github.ref_name == 'dev' && 'test' || 'prod' }}

    steps:
    - uses: actions/checkout@v2

    # removed the dotnet setup. because the self hosted agent already has the dotnet installed.
    # - name: Setup .NET Core
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: 9.x.x
    

    - name: Build with dotnet
      shell: cmd
      run: dotnet build Application/Application.csproj --configuration Release


  # dependecy on the build job
  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Debug the path
      shell: cmd
      run: echo "Path - C:\inetpub\wwwroot\$Env:APP_IIS"
      env:
        APP_IIS: ${{ secrets.APP_IIS }}



    - name: Publish with dotnet
      shell: cmd
      run: dotnet publish Application/Application.csproj --configuration Release --output .\flowbyte-app #./publish

    - name: Deploy to IIS
      shell: cmd
      run: |
        iisreset /stop
        xcopy /s /y  .\flowbyte-app\* "C:\inetpub\wwwroot\$Env:APP_IIS"\
        iisreset /start
      env:
        APP_IIS: ${{ secrets.APP_IIS }}

      
